/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    ComboField: typeof import('./src/components/ComboField.vue')['default']
    CreateDialog: typeof import('./src/components/dialogs/CreateDialog.vue')['default']
    DocTable: typeof import('./src/components/DocTable.vue')['default']
    DocViewDialog: typeof import('./src/components/dialogs/DocViewDialog.vue')['default']
    InvoiceFromOrderDialog: typeof import('./src/components/dialogs/InvoiceFromOrderDialog.vue')['default']
    ItemsTable: typeof import('./src/components/ItemsTable.vue')['default']
    LinkField: typeof import('./src/components/LinkField.vue')['default']
    PaymentDialog: typeof import('./src/components/dialogs/PaymentDialog.vue')['default']
    RecentList: typeof import('./src/components/RecentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
  }
}
